Fix type in  environment.PROMETHEUS_EXPORTER_ENABLED
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.dawarich_sidekiq.environment.PROMETHEUS_EXPORTER_ENABLED contains false, which is an invalid type, it should be a string, number, or a null
services.dawarich_app.environment.PROMETHEUS_EXPORTER_ENABLED contains false, which is an invalid type, it should be a string, number, or a null
services.dawarich_sidekiq.depends_on contains unsupported option: 'restart'
services.dawarich_app.depends_on contains unsupported option: 'restart'